language: julia
os:
  - linux
#  - osx
julia:
  - nightly
mnotifications:
  email: true
# uncomment the following lines to override the default test script
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  #- julia -e 'Pkg.add("Documenter")'
  - julia -e 'Pkg.clone(pwd()); Pkg.build("HyperDualNumbers"); Pkg.test("HyperDualNumbers"; coverage=true)'
after_success:
  #
  # Documentation
  #
  #- julia -e 'Pkg.add("Documenter")'
  #- julia -e 'cd(Pkg.dir("HyperDualNumbers")); include(joinpath("docs", "make.jl"))'
  #
  # Coverage
  #
  # push coverage results to Coveralls
  #
  - julia -e 'cd(Pkg.dir("HyperDualNumbers")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  #
  # push coverage results to Codecov
  #
  - julia -e 'cd(Pkg.dir("HyperDualNumbers")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'