name = "HyperDualNumbers"
uuid = "50ceba7f-c3ee-5a84-a6e8-3ad40456ec97"
authors = ["Rob J Goedman <goedman@icloud.com>"]
version = "4.0.3"

[deps]
Calculus = "49dc2e85-a5d0-5ad3-a950-438e2897f1b9"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NaNMath = "77ba4419-2d1f-58cd-9bb1-8ffee604a2e3"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"

[compat]
Calculus = "0.5"
NaNMath = "0.3"
SpecialFunctions = "0.10"
julia = "1"

[extras]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Documenter", "Literate", "Random", "Test"]
